name: tcapp
description: TechCampusメンバー向けサイトです。
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_gen_runner: ^5.3.2
  flutter_hooks: ^0.20.2
  font_awesome_flutter:
    git:
      url: https://github.com/fluttercommunity/font_awesome_flutter.git
      ref: master
  freezed_annotation: ^2.4.1
  go_router: ^11.1.2
  hooks_riverpod: ^2.4.3
  json_annotation: ^4.8.1
  riverpod: ^2.4.3
  url_launcher: ^6.1.14

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
